#!/bin/sh
# see: dh_installdeb(1)

set -e

# source debconf library
. /usr/share/debconf/confmodule

# restore the users file
mv /etc/freeradius/users.privacyidea /etc/freeradius/users || true

rm -f /etc/freeradius/sites-enabled/privacyidea
ln -sf /etc/freeradius/sites-available/inner-tunnel /etc/freeradius/sites-enabled/
ln -sf /etc/freeradius/sites-available/default /etc/freeradius/sites-enabled/

ucr unset privacyidea/radius/enable

#DEBHELPER#
exit 0
